function [Jf]=fun_Jacf(X)
  x=X(1);y=X(2);z=X(3);
  Jf=[3   ,            z*sin(y*z) ,  y*sin(y*z);...
      2*x ,         -2*81*(y+0.1) ,      cos(z); ...
      -y*exp(-x*y) , -x*exp(-x*y) ,          20];